import type { Metadata } from "next";
import "../globals.css";
import { getDictionary } from "./dictionaries";
import { DictionaryProvider } from "@shared/providers/DictionaryContext";
import { Footer, Header } from "@shared/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangParams {
  lang: string;
}
export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ru" }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: LangParams;
}>) {
  const dictionary = await getDictionary(params.lang);
  console.log("Dictionary:", dictionary);
  return (
    <html lang={params.lang}>
      <body>
        <DictionaryProvider value={{ dictionary }}>
          <Header />
          {children}
          <Footer />
        </DictionaryProvider>
      </body>
    </html>
  );
}
