import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@shared/ui";
import { ClientProviders } from "@shared/providers/ClientProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangParams {
  lang: string;
}

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ru" }];
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: LangParams;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang={params.lang}>
      <body>
        <ClientProviders>
          <Header />
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
