import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "./globals.css";
import { Header } from "@widgets/header/";
import { Footer } from "@shared/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
